name: attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  network_info_plus: ^4.0.1
  shared_preferences: ^2.0.15
  permission_handler: ^11.3.0
  http: ^1.2.1
  fl_chart: ^0.65.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  intl: ^0.20.2
  curved_navigation_bar: ^1.0.6
  flutter_local_notifications: ^17.0.0
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  workmanager: ^0.6.0
  dynamic_color: ^1.7.0
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  web: false
  windows: false
  macos: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
